name: Deploy to Server

on: push


jobs:
  first_job:
    runs-on: ubuntu-latest

    env:
      NAME: CodigoFacilito

    steps:
      - name: Generar archivo
        run: |
          echo "Archivo prueba, hola" >> test.log

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: test.log
  
  second_job:
    runs-on: ubuntu-latest
    needs: first_job

    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: test-artifact

      - name: Cat file
        run: cat test.log