name: Deploy to Server

on: push


jobs:
  first_job:
    runs-on: ubuntu-latest

    env:
      NAME: CodigoFacilito

    steps:
      - name: Working dir
        run: ls -al

      - name: Action
        uses: actions/checkout@v4

      - name: Working dir after actions/checkout
        run: ls -al


  second_job:
    if: ${{github.ref == 'refs/heads/main'}}
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Hola mundo ${{github.ref}}"
