name: Deploy to Server

on: push


jobs:
  first_job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        message: ["Hola", "CodigoFacilito", "Action"]
        message2: [1,2]
        runner: [ubuntu-latest, windows-latest]

    steps:
      - name: Print message
        run: echo "${{ matrix.message }}"